version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/runnify.ca
    overwrite: true
hooks:
  ApplicationStart:
    - location: Scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: Scripts/stop_server.sh
      timeout: 300
      runas: ubuntu